spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/auradocs_auradot?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: auradocsv4
    password: Aura2528@
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  data:
    elasticsearch:
      repositories:
        enabled: false
  servlet:
    multipart:
      max-file-size: 110MB
      max-request-size: 110MB

locations:
  archive-files: /var/tmp/auradocsv4/pending_docs

temp:
  location: /var/tmp/auradocsv4/temp
  signature: sign
  
jodconverter:
  local:
    enabled: true
    office-home: /usr/lib/libreoffice
    working-dir: /var/tmp/auradocsv4/temp
    process-timeout: 60000
    process-retry-interval: 250
    task-execution-timeout: 600000
    task-queue-timeout: 300000
    max-tasks-per-process: 10
    port-numbers: 2002,2003

    # kill-existing-process: true
    # process-manager: org.jodconverter.local.process.WindowsProcessManager

    environment-variables:
      PATH: "/usr/lib/libreoffice/program:$PATH"
      # PYTHONHOME: "/usr/lib/libreoffice/program/python-core-3.12.13"
      # PYTHONPATH: "/usr/lib/libreoffice/program"
    process-args:
      - "--headless"
      - "--invisible"
      - "--nologo"
      - "--nodefault"
      - "--nofirststartwizard"
      - "--norestore"

 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka
    # healthcheck:
    #   enabled: true
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}-${random.int}
    # hostname: localhost

member:
  rent:
    min: 8
    max: 31
  price:
    discount: 3
vehicle:
  default:
    model: cross over
duration: all

openapi:
  service:
    url: http://api-service:8080

management:
  health:
    elasticsearch:
      enabled: false
    reactive-elasticsearch:
      enabled: false


# url: jdbc:mysql://mysql:3306/auradocs_auradot?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
