server:
  servlet:
    context-path: /

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # issuer-uri: https://v4.auradocs.com/auth/realms/auraDOCS
          jwk-set-uri: http://keycloak:8080/auth/realms/auraDOCS/protocol/openid-connect/certs
  servlet:
    multipart:
      max-file-size: 110MB
      max-request-size: 110MB


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}-${random.int} 
    # hostname: localhost

keycloak:
  realm: auraDOCS
  auth-server-url: http://keycloak:8080/auth
  resource: auradocs
  public-client: true
  bearer-only: true
  use-resource-role-mappings: true
  # auth-endpoint: http://sso.aura.com:8181/realms/${keycloak.realm}/protocol/openid-connect/auth
  # token-url: http://sso.aura.com:8181/realms/${keycloak.realm}/protocol/openid-connect/token

openapi:
  service:
    title: AuraDocs V4 REST API
    description: Official REST API for AuraDocs V4 — a document management and workflow automation platform.
    version: 1.0.0
    url: https://v4.auradocs.com/api
  contact:
    name: AuraDOT PVT Ltd.
    email: contact@auradot.com
  keycloak:
    token-url: https://v4.auradocs.com/auth/realms/auraDOCS/protocol/openid-connect/token
springdoc: 
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /apidocs
    oauth:
      clientId: ${keycloak.resource}
      clientSecret: ${keycloak.credentials.secret}
    init-oauth: 
      client-id: ${keycloak.resource}
      client-secret: ${keycloak.credentials.secret}
      use-pkce-with-authorization-code-grant: false


management:
  health:
    elasticsearch:
      enabled: false
    reactive-elasticsearch:
      enabled: false

redis:
  host: redis
  port: 6379

wsocket:
  destination:
    prefix: /app
  broker:
    topic-prefix: /topic
    user-prefix: /queue
  endpoints:
    path: /ws
  notification:
    endpoint: /queue/notifications
  broadcast:
    endpoint: /topic/notifications
